# filename: threshold-by-metrics.py
# Code Generated by Sidekick is for learning and experimentation purposes only.
"""Read an alerts Excel export and produce a 'Threshold by Metrics' summary.

For each row we read the metric name and the observed percentage, then bucket
it into the configured band for that metric. Output: metric x band x count.
"""
import re
import sys
from pathlib import Path

import pandas as pd

# --- Threshold bands per metric (edit ranges here, not the logic) ----------
# Each band is (lower_inclusive, upper_inclusive, label).
THRESHOLDS = {
    "CPU_USAGE": [
        (90.0, 94.99, "90–94.99%"),
        (95.0, 96.99, "95–96.99%"),
        (97.0, 97.99, "97–97.99%"),
        (98.0, 98.99, "98–98.99%"),
        (99.0, 99.49, "99–99.49%"),
        (99.5, 99.89, "99.5–99.89%"),
        (99.9, 100.0, "99.9–100%"),
    ],
    "MEMORY_USAGE": [
        (90.0, 92.71, "90–92.72%"),
        (92.72, 94.99, "92.72–95%"),
        (95.0, 100.0, "95–100%"),
    ],
    "INFRASTRUCTURE-AVAILABILITY": [
        (90.0, 92.71, "90–92.72%"),
        (92.72, 94.99, "92.72–95%"),
        (95.0, 120.0, "95–120%"),
    ],
    "INFRASTRUCTURE-RESOURCE_CONTENTION": [
        (90.0, 92.71, "90–92.72%"),
        (92.72, 94.99, "92.72–95%"),
        (95.0, 120.0, "95–120%"),
    ],
    "INFRASTRUCTURE-CUSTOM_ALERT": [
        (90.0, 92.71, "90–92.72%"),
        (92.72, 94.99, "92.72–95%"),
        (95.0, 120.0, "95–120%"),
    ],
    "FAILURE_RATE": [
        (75.0, 100.0, "75–100%"),
    ],
}

# Columns searched (in order) for the observed percentage.
VALUE_COLUMNS = ["Additional information", "Description", "Short description"]
METRIC_COLUMN = "Metric Name"
PERCENT_RE = re.compile(r"(\d{1,3}(?:\.\d+)?)\s*%")


def extract_percent(row):
    """Return the first percentage found across the value columns, else None."""
    for col in VALUE_COLUMNS:
        text = row.get(col)
        if pd.isna(text):
            continue
        match = PERCENT_RE.search(str(text))
        if match:
            return float(match.group(1))
    return None


def assign_band(metric, value):
    """Map (metric, value) to its band label; flags misses for review."""
    if value is None:
        return "NO_VALUE_FOUND"
    bands = THRESHOLDS.get(str(metric).strip().upper())
    if bands is None:
        return "UNKNOWN_METRIC"
    for low, high, label in bands:
        if low <= value <= high:
            return label
    return "OUT_OF_RANGE"


def build_summary(df):
    """Add band column and return a metric x band count pivot table."""
    df = df.copy()
    df["Observed %"] = df.apply(extract_percent, axis=1)
    df["Threshold Band"] = df.apply(
        lambda r: assign_band(r.get(METRIC_COLUMN), r["Observed %"]), axis=1
    )
    summary = (
        df.groupby([METRIC_COLUMN, "Threshold Band"])
        .size()
        .reset_index(name="Alert Count")
        .sort_values([METRIC_COLUMN, "Threshold Band"])
    )
    return df, summary


def main(input_path, output_path="threshold_by_metrics.xlsx"):
    in_file = Path(input_path)
    if not in_file.exists():
        raise SystemExit(f"Input file not found: {in_file}")

    # engine chosen by extension; pandas handles .xlsx via openpyxl.
    df = pd.read_excel(in_file)
    if METRIC_COLUMN not in df.columns:
        raise SystemExit(f"Missing required column: '{METRIC_COLUMN}'")

    detailed, summary = build_summary(df)

    # Two sheets: the summary table + a detail sheet for auditing extraction.
    with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
        summary.to_excel(writer, sheet_name="Threshold by Metrics", index=False)
        keep = [METRIC_COLUMN, "Observed %", "Threshold Band"] + [
            c for c in VALUE_COLUMNS if c in detailed.columns
        ]
        detailed[keep].to_excel(writer, sheet_name="Detail", index=False)

    print(summary.to_string(index=False))
    print(f"\nSaved -> {Path(output_path).resolve()}")


if __name__ == "__main__":
    # Usage: python threshold-by-metrics.py <input.xlsx> [output.xlsx]
    args = sys.argv[1:]
    if not args:
        raise SystemExit("Usage: python threshold-by-metrics.py <input.xlsx>")
    main(*args[:2])
